name: Deploy FieldSight API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show files before zipping
        run: ls -la

      - name: Create deployment zip
        run: |
          zip -r app.zip . \
            -x "*.git*" \
            -x ".github/*" \
            -x "node_modules/*"

      - name: Show zip contents
        run: unzip -l app.zip

      - name: Deploy to Azure
        run: |
          curl -X POST \
            -u "${{ secrets.AZURE_WEBAPP_USERNAME }}:${{ secrets.AZURE_WEBAPP_PASSWORD }}" \
            -H "Content-Type: application/zip" \
            --data-binary @app.zip \
            https://fieldsight-api-gaf0fndvbhg2fshs.scm.swedencentral-01.azurewebsites.net/api/zipdeploy